services:
    # adapter: locale
    I18nBundle\Adapter\Locale\AbstractLocale:
        abstract: true
        public: false
        autowire: true

    I18nBundle\Adapter\Locale\System:
        parent: I18nBundle\Adapter\Locale\AbstractLocale
        public: false
        tags:
            - { name: i18n.adapter.locale, alias: system }

    I18nBundle\Adapter\Locale\AcceptLanguageHeader:
        parent: I18nBundle\Adapter\Locale\AbstractLocale
        public: false
        tags:
            - { name: i18n.adapter.locale, alias: browser }

    # adapter: pathGenerator
    I18nBundle\Adapter\PathGenerator\AbstractPathGenerator:
        abstract: true
        public: false
        autowire: true

    I18nBundle\Adapter\PathGenerator\StaticRoute:
        parent: I18nBundle\Adapter\PathGenerator\AbstractPathGenerator
        public: false
        tags:
            - { name: i18n.adapter.path.generator, alias: static_route }
        calls:
            - ['setUrlGenerator', ['@router']]
            - ['setRequest', ['@request_stack']]

    I18nBundle\Adapter\PathGenerator\Document:
        parent: I18nBundle\Adapter\PathGenerator\AbstractPathGenerator
        public: false
        tags:
            - { name: i18n.adapter.path.generator, alias: document }

    # adapter: context
    I18nBundle\Adapter\Context\AbstractContext:
        abstract: true
        public: false
        autowire: true

    I18nBundle\Adapter\Context\Country:
        parent: I18nBundle\Adapter\Context\AbstractContext
        public: false
        tags:
            - { name: i18n.adapter.context, alias: country }

    I18nBundle\Adapter\Context\Language:
        parent: I18nBundle\Adapter\Context\AbstractContext
        public: false
        tags:
            - { name: i18n.adapter.context, alias: language }

    # adapter: redirector
    I18nBundle\Adapter\Redirector\AbstractRedirector:
        abstract: true
        public: false
        autowire: true

    I18nBundle\Adapter\Redirector\CookieRedirector:
        parent: I18nBundle\Adapter\Redirector\AbstractRedirector
        public: false
        tags:
            - { name: i18n.adapter.redirector, alias: cookie, priority: 300 }

    I18nBundle\Adapter\Redirector\GeoRedirector:
        parent: I18nBundle\Adapter\Redirector\AbstractRedirector
        public: false
        tags:
            - { name: i18n.adapter.redirector, alias: geo, priority: 200 }

    I18nBundle\Adapter\Redirector\FallbackRedirector:
        parent: I18nBundle\Adapter\Redirector\AbstractRedirector
        public: false
        tags:
            - { name: i18n.adapter.redirector, alias: fallback, priority: 100 }